/*Generated by WaveMaker Studio*/

package com.nwissuesjan25.wmstudio.dao;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.math.BigDecimal;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Repository;
import org.springframework.orm.hibernate4.HibernateTemplate;

import com.wavemaker.runtime.data.dao.WMGenericDaoImpl;

import com.nwissuesjan25.wmstudio.*;
/**
* Specifies methods used to obtain and modify Table9 related information
* which is stored in the database.
*/
@Repository("WMSTUDIO.Table9Dao")
public class Table9Dao extends WMGenericDaoImpl <Table9, BigDecimal> {

    @Autowired
    @Qualifier("WMSTUDIOTemplate")
    private HibernateTemplate template;

    public HibernateTemplate getTemplate() {
        return this.template;
    }
}

