/*Generated by WaveMaker Studio*/

package com.nwissuesjan25.wmstudio.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/




import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;

import com.nwissuesjan25.wmstudio.*;

/**
 * Service object for domain model class Countries.
 * @see com.nwissuesjan25.wmstudio.Countries
 */

public interface CountriesService {
   /**
	 * Creates a new countries.
	 * 
	 * @param created
	 *            The information of the created countries.
	 * @return The created countries.
	 */
	public Countries create(Countries created);

	/**
	 * Deletes a countries.
	 * 
	 * @param countriesId
	 *            The id of the deleted countries.
	 * @return The deleted countries.
	 * @throws EntityNotFoundException
	 *             if no countries is found with the given id.
	 */
	public Countries delete(String countriesId) throws EntityNotFoundException;

	/**
	 * Finds all countriess.
	 * 
	 * @return A list of countriess.
	 */
	public Page<Countries> findAll(QueryFilter[] queryFilters, Pageable pageable);
	
	public Page<Countries> findAll(Pageable pageable);
	
	/**
	 * Finds countries by id.
	 * 
	 * @param id
	 *            The id of the wanted countries.
	 * @return The found countries. If no countries is found, this method returns
	 *         null.
	 */
	public Countries findById(String id) throws
	 EntityNotFoundException;
	/**
	 * Updates the information of a countries.
	 * 
	 * @param updated
	 *            The information of the updated countries.
	 * @return The updated countries.
	 * @throws EntityNotFoundException
	 *             if no countries is found with given id.
	 */
	public Countries update(Countries updated) throws EntityNotFoundException;

	/**
	 * Retrieve the total count of the countriess in the repository.
	 * 
	 * @param None
	 *            .
	 * @return The count of the countries.
	 */

	public long countAll();


    public Page<Countries> findAssociatedValues(Object value, String entityName, String key,  Pageable pageable);


}

