/*Generated by WaveMaker Studio*/

package com.nwissuesjan25.wmstudio.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/




import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;

import com.nwissuesjan25.wmstudio.*;

/**
 * Service object for domain model class EmpDetailsView.
 * @see com.nwissuesjan25.wmstudio.EmpDetailsView
 */

public interface EmpDetailsViewService {
   /**
	 * Creates a new empdetailsview.
	 * 
	 * @param created
	 *            The information of the created empdetailsview.
	 * @return The created empdetailsview.
	 */
	public EmpDetailsView create(EmpDetailsView created);

	/**
	 * Deletes a empdetailsview.
	 * 
	 * @param empdetailsviewId
	 *            The id of the deleted empdetailsview.
	 * @return The deleted empdetailsview.
	 * @throws EntityNotFoundException
	 *             if no empdetailsview is found with the given id.
	 */
	public EmpDetailsView delete(EmpDetailsViewId empdetailsviewId) throws EntityNotFoundException;

	/**
	 * Finds all empdetailsviews.
	 * 
	 * @return A list of empdetailsviews.
	 */
	public Page<EmpDetailsView> findAll(QueryFilter[] queryFilters, Pageable pageable);
	
	public Page<EmpDetailsView> findAll(Pageable pageable);
	
	/**
	 * Finds empdetailsview by id.
	 * 
	 * @param id
	 *            The id of the wanted empdetailsview.
	 * @return The found empdetailsview. If no empdetailsview is found, this method returns
	 *         null.
	 */
	public EmpDetailsView findById(EmpDetailsViewId id) throws
	 EntityNotFoundException;
	/**
	 * Updates the information of a empdetailsview.
	 * 
	 * @param updated
	 *            The information of the updated empdetailsview.
	 * @return The updated empdetailsview.
	 * @throws EntityNotFoundException
	 *             if no empdetailsview is found with given id.
	 */
	public EmpDetailsView update(EmpDetailsView updated) throws EntityNotFoundException;

	/**
	 * Retrieve the total count of the empdetailsviews in the repository.
	 * 
	 * @param None
	 *            .
	 * @return The count of the empdetailsview.
	 */

	public long countAll();


    public Page<EmpDetailsView> findAssociatedValues(Object value, String entityName, String key,  Pageable pageable);


}

