/*Generated by WaveMaker Studio*/

package com.nwissuesjan25.wmstudio.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/





import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;

import com.wavemaker.runtime.data.dao.*;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;

import com.nwissuesjan25.wmstudio.*;


/**
 * ServiceImpl object for domain model class Jobs.
 * @see com.nwissuesjan25.wmstudio.Jobs
 */
@Service("WMSTUDIO.JobsService")
public class JobsServiceImpl implements JobsService {


    private static final Logger LOGGER = LoggerFactory.getLogger(JobsServiceImpl.class);

    @Autowired
    @Qualifier("WMSTUDIO.JobsDao")
    private WMGenericDao<Jobs, String> wmGenericDao;

    public void setWMGenericDao(WMGenericDao<Jobs, String> wmGenericDao){
        this.wmGenericDao = wmGenericDao;
    }
     @Transactional(readOnly = true, value = "WMSTUDIOTransactionManager")
     public Page<Jobs> findAssociatedValues(Object value, String entityName, String key,  Pageable pageable){
          LOGGER.debug("Fetching all associated");
          return this.wmGenericDao.getAssociatedObjects(value, entityName, key, pageable);
     }

    @Transactional(value = "WMSTUDIOTransactionManager")
    @Override
    public Jobs create(Jobs jobs) {
        LOGGER.debug("Creating a new jobs with information: {}" , jobs);
        return this.wmGenericDao.create(jobs);
    }

    @Transactional(rollbackFor = EntityNotFoundException.class, value = "WMSTUDIOTransactionManager")
    @Override
    public Jobs delete(String jobsId) throws EntityNotFoundException {
        LOGGER.debug("Deleting jobs with id: {}" , jobsId);
        Jobs deleted = this.wmGenericDao.findById(jobsId);
        if (deleted == null) {
            LOGGER.debug("No jobs found with id: {}" , jobsId);
            throw new EntityNotFoundException(String.valueOf(jobsId));
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

    @Transactional(readOnly = true, value = "WMSTUDIOTransactionManager")
    @Override
    public Page<Jobs> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all jobss");
        return this.wmGenericDao.search(queryFilters, pageable);
    }
    
    @Transactional(readOnly = true, value = "WMSTUDIOTransactionManager")
    @Override
    public Page<Jobs> findAll(Pageable pageable) {
        LOGGER.debug("Finding all jobss");
        return this.wmGenericDao.search(null, pageable);
    }

    @Transactional(readOnly = true, value = "WMSTUDIOTransactionManager")
    @Override
    public Jobs findById(String id) throws EntityNotFoundException {
        LOGGER.debug("Finding jobs by id: {}" , id);
        Jobs jobs=this.wmGenericDao.findById(id);
        if(jobs==null){
            LOGGER.debug("No jobs found with id: {}" , id);
            throw new EntityNotFoundException(String.valueOf(id));
        }
        return jobs;
    }
    @Transactional(rollbackFor = EntityNotFoundException.class, value = "WMSTUDIOTransactionManager")
    @Override
    public Jobs update(Jobs updated) throws EntityNotFoundException {
        LOGGER.debug("Updating jobs with information: {}" , updated);
        this.wmGenericDao.update(updated);

        String id = (String)updated.getJobId();

        return this.wmGenericDao.findById(id);
    }

    @Transactional(readOnly = true, value = "WMSTUDIOTransactionManager")
    @Override
    public long countAll() {
        return this.wmGenericDao.count();
    }
}


