/*Generated by WaveMaker Studio*/

package com.nwissuesjan25.wmstudio.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.math.BigDecimal;


import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;

import com.nwissuesjan25.wmstudio.*;

/**
 * Service object for domain model class Regions.
 * @see com.nwissuesjan25.wmstudio.Regions
 */

public interface RegionsService {
   /**
	 * Creates a new regions.
	 * 
	 * @param created
	 *            The information of the created regions.
	 * @return The created regions.
	 */
	public Regions create(Regions created);

	/**
	 * Deletes a regions.
	 * 
	 * @param regionsId
	 *            The id of the deleted regions.
	 * @return The deleted regions.
	 * @throws EntityNotFoundException
	 *             if no regions is found with the given id.
	 */
	public Regions delete(BigDecimal regionsId) throws EntityNotFoundException;

	/**
	 * Finds all regionss.
	 * 
	 * @return A list of regionss.
	 */
	public Page<Regions> findAll(QueryFilter[] queryFilters, Pageable pageable);
	
	public Page<Regions> findAll(Pageable pageable);
	
	/**
	 * Finds regions by id.
	 * 
	 * @param id
	 *            The id of the wanted regions.
	 * @return The found regions. If no regions is found, this method returns
	 *         null.
	 */
	public Regions findById(BigDecimal id) throws
	 EntityNotFoundException;
	/**
	 * Updates the information of a regions.
	 * 
	 * @param updated
	 *            The information of the updated regions.
	 * @return The updated regions.
	 * @throws EntityNotFoundException
	 *             if no regions is found with given id.
	 */
	public Regions update(Regions updated) throws EntityNotFoundException;

	/**
	 * Retrieve the total count of the regionss in the repository.
	 * 
	 * @param None
	 *            .
	 * @return The count of the regions.
	 */

	public long countAll();


    public Page<Regions> findAssociatedValues(Object value, String entityName, String key,  Pageable pageable);


}

