/*Generated by WaveMaker Studio*/

package com.nwissuesjan25.wmstudio.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.math.BigDecimal;


import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;

import com.nwissuesjan25.wmstudio.*;

/**
 * Service object for domain model class Table9.
 * @see com.nwissuesjan25.wmstudio.Table9
 */

public interface Table9Service {
   /**
	 * Creates a new table9.
	 * 
	 * @param created
	 *            The information of the created table9.
	 * @return The created table9.
	 */
	public Table9 create(Table9 created);

	/**
	 * Deletes a table9.
	 * 
	 * @param table9Id
	 *            The id of the deleted table9.
	 * @return The deleted table9.
	 * @throws EntityNotFoundException
	 *             if no table9 is found with the given id.
	 */
	public Table9 delete(BigDecimal table9Id) throws EntityNotFoundException;

	/**
	 * Finds all table9s.
	 * 
	 * @return A list of table9s.
	 */
	public Page<Table9> findAll(QueryFilter[] queryFilters, Pageable pageable);
	
	public Page<Table9> findAll(Pageable pageable);
	
	/**
	 * Finds table9 by id.
	 * 
	 * @param id
	 *            The id of the wanted table9.
	 * @return The found table9. If no table9 is found, this method returns
	 *         null.
	 */
	public Table9 findById(BigDecimal id) throws
	 EntityNotFoundException;
	/**
	 * Updates the information of a table9.
	 * 
	 * @param updated
	 *            The information of the updated table9.
	 * @return The updated table9.
	 * @throws EntityNotFoundException
	 *             if no table9 is found with given id.
	 */
	public Table9 update(Table9 updated) throws EntityNotFoundException;

	/**
	 * Retrieve the total count of the table9s in the repository.
	 * 
	 * @param None
	 *            .
	 * @return The count of the table9.
	 */

	public long countAll();


    public Page<Table9> findAssociatedValues(Object value, String entityName, String key,  Pageable pageable);


}

