/*Generated by WaveMaker Studio*/

package com.nwissuesjan25.wmstudio.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.math.BigDecimal;



import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;

import com.wavemaker.runtime.data.dao.*;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;

import com.nwissuesjan25.wmstudio.*;


/**
 * ServiceImpl object for domain model class Table10.
 * @see com.nwissuesjan25.wmstudio.Table10
 */
@Service("WMSTUDIO.Table10Service")
public class Table10ServiceImpl implements Table10Service {


    private static final Logger LOGGER = LoggerFactory.getLogger(Table10ServiceImpl.class);

    @Autowired
    @Qualifier("WMSTUDIO.Table10Dao")
    private WMGenericDao<Table10, BigDecimal> wmGenericDao;

    public void setWMGenericDao(WMGenericDao<Table10, BigDecimal> wmGenericDao){
        this.wmGenericDao = wmGenericDao;
    }
     @Transactional(readOnly = true, value = "WMSTUDIOTransactionManager")
     public Page<Table10> findAssociatedValues(Object value, String entityName, String key,  Pageable pageable){
          LOGGER.debug("Fetching all associated");
          return this.wmGenericDao.getAssociatedObjects(value, entityName, key, pageable);
     }

    @Transactional(value = "WMSTUDIOTransactionManager")
    @Override
    public Table10 create(Table10 table10) {
        LOGGER.debug("Creating a new table10 with information: {}" , table10);
        return this.wmGenericDao.create(table10);
    }

    @Transactional(rollbackFor = EntityNotFoundException.class, value = "WMSTUDIOTransactionManager")
    @Override
    public Table10 delete(BigDecimal table10Id) throws EntityNotFoundException {
        LOGGER.debug("Deleting table10 with id: {}" , table10Id);
        Table10 deleted = this.wmGenericDao.findById(table10Id);
        if (deleted == null) {
            LOGGER.debug("No table10 found with id: {}" , table10Id);
            throw new EntityNotFoundException(String.valueOf(table10Id));
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

    @Transactional(readOnly = true, value = "WMSTUDIOTransactionManager")
    @Override
    public Page<Table10> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all table10s");
        return this.wmGenericDao.search(queryFilters, pageable);
    }
    
    @Transactional(readOnly = true, value = "WMSTUDIOTransactionManager")
    @Override
    public Page<Table10> findAll(Pageable pageable) {
        LOGGER.debug("Finding all table10s");
        return this.wmGenericDao.search(null, pageable);
    }

    @Transactional(readOnly = true, value = "WMSTUDIOTransactionManager")
    @Override
    public Table10 findById(BigDecimal id) throws EntityNotFoundException {
        LOGGER.debug("Finding table10 by id: {}" , id);
        Table10 table10=this.wmGenericDao.findById(id);
        if(table10==null){
            LOGGER.debug("No table10 found with id: {}" , id);
            throw new EntityNotFoundException(String.valueOf(id));
        }
        return table10;
    }
    @Transactional(rollbackFor = EntityNotFoundException.class, value = "WMSTUDIOTransactionManager")
    @Override
    public Table10 update(Table10 updated) throws EntityNotFoundException {
        LOGGER.debug("Updating table10 with information: {}" , updated);
        this.wmGenericDao.update(updated);

        BigDecimal id = (BigDecimal)updated.getId();

        return this.wmGenericDao.findById(id);
    }

    @Transactional(readOnly = true, value = "WMSTUDIOTransactionManager")
    @Override
    public long countAll() {
        return this.wmGenericDao.count();
    }
}


