/*Generated by WaveMaker Studio*/

package com.nwissuesjan25.wmstudio.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.math.BigDecimal;


import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;

import com.nwissuesjan25.wmstudio.*;

/**
 * Service object for domain model class Table10.
 * @see com.nwissuesjan25.wmstudio.Table10
 */

public interface Table10Service {
   /**
	 * Creates a new table10.
	 * 
	 * @param created
	 *            The information of the created table10.
	 * @return The created table10.
	 */
	public Table10 create(Table10 created);

	/**
	 * Deletes a table10.
	 * 
	 * @param table10Id
	 *            The id of the deleted table10.
	 * @return The deleted table10.
	 * @throws EntityNotFoundException
	 *             if no table10 is found with the given id.
	 */
	public Table10 delete(BigDecimal table10Id) throws EntityNotFoundException;

	/**
	 * Finds all table10s.
	 * 
	 * @return A list of table10s.
	 */
	public Page<Table10> findAll(QueryFilter[] queryFilters, Pageable pageable);
	
	public Page<Table10> findAll(Pageable pageable);
	
	/**
	 * Finds table10 by id.
	 * 
	 * @param id
	 *            The id of the wanted table10.
	 * @return The found table10. If no table10 is found, this method returns
	 *         null.
	 */
	public Table10 findById(BigDecimal id) throws
	 EntityNotFoundException;
	/**
	 * Updates the information of a table10.
	 * 
	 * @param updated
	 *            The information of the updated table10.
	 * @return The updated table10.
	 * @throws EntityNotFoundException
	 *             if no table10 is found with given id.
	 */
	public Table10 update(Table10 updated) throws EntityNotFoundException;

	/**
	 * Retrieve the total count of the table10s in the repository.
	 * 
	 * @param None
	 *            .
	 * @return The count of the table10.
	 */

	public long countAll();


    public Page<Table10> findAssociatedValues(Object value, String entityName, String key,  Pageable pageable);


}

