/*Generated by WaveMaker Studio*/

package com.nwissuesjan25.wmstudio.controller;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import com.nwissuesjan25.wmstudio.service.CountriesService;
import com.nwissuesjan25.wmstudio.service.LocationsService;


import java.io.*;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.hibernate.TypeMismatchException;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.multipart.MultipartHttpServletRequest;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.util.WMMultipartUtils;
import com.wavemaker.runtime.util.WMRuntimeUtils;
import com.wavemaker.runtime.file.model.DownloadResponse;
import com.wordnik.swagger.annotations.*;

import com.nwissuesjan25.wmstudio.*;
import com.nwissuesjan25.wmstudio.service.*;


/**
 * Controller object for domain model class Countries.
 * @see com.nwissuesjan25.wmstudio.Countries
 */

@RestController(value = "WMSTUDIO.CountriesController")
@Api(value = "/WMSTUDIO/Countries", description = "Exposes APIs to work with Countries resource.")
@RequestMapping("/WMSTUDIO/Countries")
public class CountriesController {

    private static final Logger LOGGER = LoggerFactory.getLogger(CountriesController.class);

	@Autowired
	@Qualifier("WMSTUDIO.CountriesService")
	private CountriesService countriesService;


    @Autowired
    @Qualifier("WMSTUDIO.LocationsService")
    private LocationsService locationsService;


	@RequestMapping(value = "/search", method = RequestMethod.POST)
	@ApiOperation(value = "Returns the list of Countries instances matching the search criteria.")
	public Page<Countries> findCountriess( Pageable pageable, @RequestBody QueryFilter[] queryFilters) {
		LOGGER.debug("Rendering Countriess list");
		return countriesService.findAll(queryFilters, pageable);
	}

	@RequestMapping(value = "/", method = RequestMethod.GET)
	@ApiOperation(value = "Returns the list of Countries instances.")
	public Page<Countries> getCountriess(Pageable pageable) {
		LOGGER.debug("Rendering Countriess list");
		return countriesService.findAll(pageable);
	}

	@RequestMapping(value = "/count", method = RequestMethod.GET)
	@ApiOperation(value = "Returns the total count of Countries instances.")
	public Long countAllCountriess() {
		LOGGER.debug("counting Countriess");
		Long count = countriesService.countAll();
		return count;
	}


    @RequestMapping(value = "/{id:.+}", method = RequestMethod.GET)
    @ApiOperation(value = "Returns the Countries instance associated with the given id.")
    public Countries getCountries(@PathVariable("id") String id) throws EntityNotFoundException {
        LOGGER.debug("Getting Countries with id: {}" , id);
        Countries instance = countriesService.findById(id);
        LOGGER.debug("Countries details with id: {}" , instance);
        return instance;
    }
    @RequestMapping(value = "/{id:.+}", method = RequestMethod.DELETE)
    @ApiOperation(value = "Deletes the Countries instance associated with the given id.")
    public boolean deleteCountries(@PathVariable("id") String id) throws EntityNotFoundException {
        LOGGER.debug("Deleting Countries with id: {}" , id);
        Countries deleted = countriesService.delete(id);
        return deleted != null;
    }

    @RequestMapping(value = "/{id:.+}", method = RequestMethod.PUT)
    @ApiOperation(value = "Updates the Countries instance associated with the given id.")
    public Countries editCountries(@PathVariable("id") String id, @RequestBody Countries instance) throws EntityNotFoundException {
        LOGGER.debug("Editing Countries with id: {}" , instance.getCountryId());
        instance.setCountryId(id);
        instance = countriesService.update(instance);
        LOGGER.debug("Countries details with id: {}" , instance);
        return instance;
    }


    @RequestMapping(value="/{id:.+}/locationses", method=RequestMethod.GET)
    @ApiOperation(value = "Gets the locationses instance associated with the given id.")
     public Page<Locations> findAssociatedlocationses(Pageable pageable, @PathVariable("id") String id){
        LOGGER.debug("Fetching all associated locationses");
        return locationsService.findAssociatedValues(id,"countries","countryId", pageable);
   }



	@RequestMapping(value = "/", method = RequestMethod.POST)
	@ApiOperation(value = "Creates a new Countries instance.")
	public Countries createCountries(@RequestBody Countries instance) {
		LOGGER.debug("Create Countries with information: {}" , instance);
		instance = countriesService.create(instance);
		LOGGER.debug("Created Countries with information: {}" , instance);
	    return instance;
	}

	/**
	 * This setter method should only be used by unit tests
	 * 
	 * @param service
	 */
	protected void setCountriesService(CountriesService service) {
		this.countriesService = service;
	}
}

