/*Generated by WaveMaker Studio*/

package com.nwissuesjan25.wmstudio.controller;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import com.nwissuesjan25.wmstudio.service.DepartmentsService;
import com.nwissuesjan25.wmstudio.service.LocationsService;


import java.io.*;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.hibernate.TypeMismatchException;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.multipart.MultipartHttpServletRequest;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.util.WMMultipartUtils;
import com.wavemaker.runtime.util.WMRuntimeUtils;
import com.wavemaker.runtime.file.model.DownloadResponse;
import com.wordnik.swagger.annotations.*;

import com.nwissuesjan25.wmstudio.*;
import com.nwissuesjan25.wmstudio.service.*;


/**
 * Controller object for domain model class Locations.
 * @see com.nwissuesjan25.wmstudio.Locations
 */

@RestController(value = "WMSTUDIO.LocationsController")
@Api(value = "/WMSTUDIO/Locations", description = "Exposes APIs to work with Locations resource.")
@RequestMapping("/WMSTUDIO/Locations")
public class LocationsController {

    private static final Logger LOGGER = LoggerFactory.getLogger(LocationsController.class);

	@Autowired
	@Qualifier("WMSTUDIO.LocationsService")
	private LocationsService locationsService;


    @Autowired
    @Qualifier("WMSTUDIO.DepartmentsService")
    private DepartmentsService departmentsService;


	@RequestMapping(value = "/search", method = RequestMethod.POST)
	@ApiOperation(value = "Returns the list of Locations instances matching the search criteria.")
	public Page<Locations> findLocationss( Pageable pageable, @RequestBody QueryFilter[] queryFilters) {
		LOGGER.debug("Rendering Locationss list");
		return locationsService.findAll(queryFilters, pageable);
	}

	@RequestMapping(value = "/", method = RequestMethod.GET)
	@ApiOperation(value = "Returns the list of Locations instances.")
	public Page<Locations> getLocationss(Pageable pageable) {
		LOGGER.debug("Rendering Locationss list");
		return locationsService.findAll(pageable);
	}

	@RequestMapping(value = "/count", method = RequestMethod.GET)
	@ApiOperation(value = "Returns the total count of Locations instances.")
	public Long countAllLocationss() {
		LOGGER.debug("counting Locationss");
		Long count = locationsService.countAll();
		return count;
	}


    @RequestMapping(value = "/{id:.+}", method = RequestMethod.GET)
    @ApiOperation(value = "Returns the Locations instance associated with the given id.")
    public Locations getLocations(@PathVariable("id") short id) throws EntityNotFoundException {
        LOGGER.debug("Getting Locations with id: {}" , id);
        Locations instance = locationsService.findById(id);
        LOGGER.debug("Locations details with id: {}" , instance);
        return instance;
    }
    @RequestMapping(value = "/{id:.+}", method = RequestMethod.DELETE)
    @ApiOperation(value = "Deletes the Locations instance associated with the given id.")
    public boolean deleteLocations(@PathVariable("id") short id) throws EntityNotFoundException {
        LOGGER.debug("Deleting Locations with id: {}" , id);
        Locations deleted = locationsService.delete(id);
        return deleted != null;
    }

    @RequestMapping(value = "/{id:.+}", method = RequestMethod.PUT)
    @ApiOperation(value = "Updates the Locations instance associated with the given id.")
    public Locations editLocations(@PathVariable("id") short id, @RequestBody Locations instance) throws EntityNotFoundException {
        LOGGER.debug("Editing Locations with id: {}" , instance.getLocationId());
        instance.setLocationId(id);
        instance = locationsService.update(instance);
        LOGGER.debug("Locations details with id: {}" , instance);
        return instance;
    }


    @RequestMapping(value="/{id:.+}/departmentses", method=RequestMethod.GET)
    @ApiOperation(value = "Gets the departmentses instance associated with the given id.")
     public Page<Departments> findAssociateddepartmentses(Pageable pageable, @PathVariable("id") short id){
        LOGGER.debug("Fetching all associated departmentses");
        return departmentsService.findAssociatedValues(id,"locations","locationId", pageable);
   }



	@RequestMapping(value = "/", method = RequestMethod.POST)
	@ApiOperation(value = "Creates a new Locations instance.")
	public Locations createLocations(@RequestBody Locations instance) {
		LOGGER.debug("Create Locations with information: {}" , instance);
		instance = locationsService.create(instance);
		LOGGER.debug("Created Locations with information: {}" , instance);
	    return instance;
	}

	/**
	 * This setter method should only be used by unit tests
	 * 
	 * @param service
	 */
	protected void setLocationsService(LocationsService service) {
		this.locationsService = service;
	}
}

