/*Generated by WaveMaker Studio*/

package com.nwissuesjan25.wmstudio;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import javax.persistence.PrimaryKeyJoinColumn;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;


import java.util.Arrays;

import javax.persistence.Transient;
import javax.persistence.CascadeType;
import javax.persistence.UniqueConstraint;



/**
 * EmpDetailsView generated by hbm2java
 */
@Entity
@Table(name="`EMP_DETAILS_VIEW`"
    ,schema="HR"
)
@IdClass(value=EmpDetailsViewId.class)
public class EmpDetailsView  implements java.io.Serializable {

    private Integer employeeId;
    private String jobId;
    private Integer managerId;
    private Short departmentId;
    private Short locationId;
    private String countryId;
    private String firstName;
    private String lastName;
    private BigDecimal salary;
    private BigDecimal commissionPct;
    private String departmentName;
    private String jobTitle;
    private String city;
    private String stateProvince;
    private String countryName;
    private String regionName;

    public EmpDetailsView() {
    }


    @Id 
    

    @Column(name="`EMPLOYEE_ID`", nullable=false, insertable=false, updatable=false, precision=6)
    public Integer getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }
    @Id 
    

    @Column(name="`JOB_ID`", nullable=false, insertable=false, updatable=false, length=10)
    public String getJobId() {
        return this.jobId;
    }
    
    public void setJobId(String jobId) {
        this.jobId = jobId;
    }
    @Id 
    

    @Column(name="`MANAGER_ID`", insertable=false, updatable=false, precision=6)
    public Integer getManagerId() {
        return this.managerId;
    }
    
    public void setManagerId(Integer managerId) {
        this.managerId = managerId;
    }
    @Id 
    

    @Column(name="`DEPARTMENT_ID`", insertable=false, updatable=false, precision=4)
    public Short getDepartmentId() {
        return this.departmentId;
    }
    
    public void setDepartmentId(Short departmentId) {
        this.departmentId = departmentId;
    }
    @Id 
    

    @Column(name="`LOCATION_ID`", insertable=false, updatable=false, precision=4)
    public Short getLocationId() {
        return this.locationId;
    }
    
    public void setLocationId(Short locationId) {
        this.locationId = locationId;
    }
    @Id 
    

    @Column(name="`COUNTRY_ID`", insertable=false, updatable=false, length=2)
    public String getCountryId() {
        return this.countryId;
    }
    
    public void setCountryId(String countryId) {
        this.countryId = countryId;
    }
    @Id 
    

    @Column(name="`FIRST_NAME`", insertable=false, updatable=false, length=20)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    @Id 
    

    @Column(name="`LAST_NAME`", nullable=false, insertable=false, updatable=false, length=25)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    @Id 
    

    @Column(name="`SALARY`", insertable=false, updatable=false, precision=8)
    public BigDecimal getSalary() {
        return this.salary;
    }
    
    public void setSalary(BigDecimal salary) {
        this.salary = salary;
    }
    @Id 
    

    @Column(name="`COMMISSION_PCT`", insertable=false, updatable=false, precision=2)
    public BigDecimal getCommissionPct() {
        return this.commissionPct;
    }
    
    public void setCommissionPct(BigDecimal commissionPct) {
        this.commissionPct = commissionPct;
    }
    @Id 
    

    @Column(name="`DEPARTMENT_NAME`", nullable=false, insertable=false, updatable=false, length=30)
    public String getDepartmentName() {
        return this.departmentName;
    }
    
    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName;
    }
    @Id 
    

    @Column(name="`JOB_TITLE`", nullable=false, insertable=false, updatable=false, length=35)
    public String getJobTitle() {
        return this.jobTitle;
    }
    
    public void setJobTitle(String jobTitle) {
        this.jobTitle = jobTitle;
    }
    @Id 
    

    @Column(name="`CITY`", nullable=false, insertable=false, updatable=false, length=30)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    @Id 
    

    @Column(name="`STATE_PROVINCE`", insertable=false, updatable=false, length=25)
    public String getStateProvince() {
        return this.stateProvince;
    }
    
    public void setStateProvince(String stateProvince) {
        this.stateProvince = stateProvince;
    }
    @Id 
    

    @Column(name="`COUNTRY_NAME`", insertable=false, updatable=false, length=40)
    public String getCountryName() {
        return this.countryName;
    }
    
    public void setCountryName(String countryName) {
        this.countryName = countryName;
    }
    @Id 
    

    @Column(name="`REGION_NAME`", insertable=false, updatable=false, length=25)
    public String getRegionName() {
        return this.regionName;
    }
    
    public void setRegionName(String regionName) {
        this.regionName = regionName;
    }





    public boolean equals(Object o) {
         if (this == o) return true;
		 if ( (o == null )) return false;
		 if ( !(o instanceof EmpDetailsView) )
		    return false;

		 EmpDetailsView that = (EmpDetailsView) o;

         return ( (this.getEmployeeId()==that.getEmployeeId()) || ( this.getEmployeeId()!=null && that.getEmployeeId()!=null && this.getEmployeeId().equals(that.getEmployeeId()) ) )
 && ( (this.getJobId()==that.getJobId()) || ( this.getJobId()!=null && that.getJobId()!=null && this.getJobId().equals(that.getJobId()) ) )
 && ( (this.getManagerId()==that.getManagerId()) || ( this.getManagerId()!=null && that.getManagerId()!=null && this.getManagerId().equals(that.getManagerId()) ) )
 && ( (this.getDepartmentId()==that.getDepartmentId()) || ( this.getDepartmentId()!=null && that.getDepartmentId()!=null && this.getDepartmentId().equals(that.getDepartmentId()) ) )
 && ( (this.getLocationId()==that.getLocationId()) || ( this.getLocationId()!=null && that.getLocationId()!=null && this.getLocationId().equals(that.getLocationId()) ) )
 && ( (this.getCountryId()==that.getCountryId()) || ( this.getCountryId()!=null && that.getCountryId()!=null && this.getCountryId().equals(that.getCountryId()) ) )
 && ( (this.getFirstName()==that.getFirstName()) || ( this.getFirstName()!=null && that.getFirstName()!=null && this.getFirstName().equals(that.getFirstName()) ) )
 && ( (this.getLastName()==that.getLastName()) || ( this.getLastName()!=null && that.getLastName()!=null && this.getLastName().equals(that.getLastName()) ) )
 && ( (this.getSalary()==that.getSalary()) || ( this.getSalary()!=null && that.getSalary()!=null && this.getSalary().equals(that.getSalary()) ) )
 && ( (this.getCommissionPct()==that.getCommissionPct()) || ( this.getCommissionPct()!=null && that.getCommissionPct()!=null && this.getCommissionPct().equals(that.getCommissionPct()) ) )
 && ( (this.getDepartmentName()==that.getDepartmentName()) || ( this.getDepartmentName()!=null && that.getDepartmentName()!=null && this.getDepartmentName().equals(that.getDepartmentName()) ) )
 && ( (this.getJobTitle()==that.getJobTitle()) || ( this.getJobTitle()!=null && that.getJobTitle()!=null && this.getJobTitle().equals(that.getJobTitle()) ) )
 && ( (this.getCity()==that.getCity()) || ( this.getCity()!=null && that.getCity()!=null && this.getCity().equals(that.getCity()) ) )
 && ( (this.getStateProvince()==that.getStateProvince()) || ( this.getStateProvince()!=null && that.getStateProvince()!=null && this.getStateProvince().equals(that.getStateProvince()) ) )
 && ( (this.getCountryName()==that.getCountryName()) || ( this.getCountryName()!=null && that.getCountryName()!=null && this.getCountryName().equals(that.getCountryName()) ) )
 && ( (this.getRegionName()==that.getRegionName()) || ( this.getRegionName()!=null && that.getRegionName()!=null && this.getRegionName().equals(that.getRegionName()) ) );
    }

    public int hashCode() {
         int result = 17;

         result = 37 * result + ( getEmployeeId() == null ? 0 : this.getEmployeeId().hashCode() );
         result = 37 * result + ( getJobId() == null ? 0 : this.getJobId().hashCode() );
         result = 37 * result + ( getManagerId() == null ? 0 : this.getManagerId().hashCode() );
         result = 37 * result + ( getDepartmentId() == null ? 0 : this.getDepartmentId().hashCode() );
         result = 37 * result + ( getLocationId() == null ? 0 : this.getLocationId().hashCode() );
         result = 37 * result + ( getCountryId() == null ? 0 : this.getCountryId().hashCode() );
         result = 37 * result + ( getFirstName() == null ? 0 : this.getFirstName().hashCode() );
         result = 37 * result + ( getLastName() == null ? 0 : this.getLastName().hashCode() );
         result = 37 * result + ( getSalary() == null ? 0 : this.getSalary().hashCode() );
         result = 37 * result + ( getCommissionPct() == null ? 0 : this.getCommissionPct().hashCode() );
         result = 37 * result + ( getDepartmentName() == null ? 0 : this.getDepartmentName().hashCode() );
         result = 37 * result + ( getJobTitle() == null ? 0 : this.getJobTitle().hashCode() );
         result = 37 * result + ( getCity() == null ? 0 : this.getCity().hashCode() );
         result = 37 * result + ( getStateProvince() == null ? 0 : this.getStateProvince().hashCode() );
         result = 37 * result + ( getCountryName() == null ? 0 : this.getCountryName().hashCode() );
         result = 37 * result + ( getRegionName() == null ? 0 : this.getRegionName().hashCode() );

         return result;
    }


}

