/*Generated by WaveMaker Studio*/

package com.nwissuesjan25.wmstudio;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import javax.persistence.PrimaryKeyJoinColumn;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


import java.util.Arrays;

import javax.persistence.Transient;
import javax.persistence.CascadeType;
import javax.persistence.UniqueConstraint;



/**
 * JobHistory generated by hbm2java
 */
@Entity
@Table(name="`JOB_HISTORY`"
    ,schema="HR"
)
@IdClass(value=JobHistoryId.class)
public class JobHistory  implements java.io.Serializable {

    private Integer employeeId;
    private Date startDate;
    private Date endDate;
    private Departments departments;
    private Employees employees;
    private Jobs jobs;

    public JobHistory() {
    }


    @Id 
    

    @Column(name="`EMPLOYEE_ID`", nullable=false, insertable=false, updatable=false, precision=6)
    public Integer getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }
    @Id 
    @Temporal(TemporalType.DATE)

    @Column(name="`START_DATE`", nullable=false, insertable=false, updatable=false)
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    @Temporal(TemporalType.DATE)

    @Column(name="`END_DATE`", nullable=false)
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="`DEPARTMENT_ID`")
    public Departments getDepartments() {
        return this.departments;
    }
    
    public void setDepartments(Departments departments) {
        this.departments = departments;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="`EMPLOYEE_ID`", nullable=false, insertable=false, updatable=false)
    public Employees getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Employees employees) {
        
        this.employeeId = employees.getEmployeeId();
      
        this.employees = employees;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="`JOB_ID`", nullable=false)
    public Jobs getJobs() {
        return this.jobs;
    }
    
    public void setJobs(Jobs jobs) {
        this.jobs = jobs;
    }





    public boolean equals(Object o) {
         if (this == o) return true;
		 if ( (o == null )) return false;
		 if ( !(o instanceof JobHistory) )
		    return false;

		 JobHistory that = (JobHistory) o;

         return ( (this.getEmployeeId()==that.getEmployeeId()) || ( this.getEmployeeId()!=null && that.getEmployeeId()!=null && this.getEmployeeId().equals(that.getEmployeeId()) ) )
 && ( (this.getStartDate()==that.getStartDate()) || ( this.getStartDate()!=null && that.getStartDate()!=null && this.getStartDate().equals(that.getStartDate()) ) )
 && ( (this.getEndDate()==that.getEndDate()) || ( this.getEndDate()!=null && that.getEndDate()!=null && this.getEndDate().equals(that.getEndDate()) ) )
 && ( (this.getDepartments()==that.getDepartments()) || ( this.getDepartments()!=null && that.getDepartments()!=null && this.getDepartments().equals(that.getDepartments()) ) )
 && ( (this.getEmployees()==that.getEmployees()) || ( this.getEmployees()!=null && that.getEmployees()!=null && this.getEmployees().equals(that.getEmployees()) ) )
 && ( (this.getJobs()==that.getJobs()) || ( this.getJobs()!=null && that.getJobs()!=null && this.getJobs().equals(that.getJobs()) ) );
    }

    public int hashCode() {
         int result = 17;

         result = 37 * result + ( getEmployeeId() == null ? 0 : this.getEmployeeId().hashCode() );
         result = 37 * result + ( getStartDate() == null ? 0 : this.getStartDate().hashCode() );
         result = 37 * result + ( getEndDate() == null ? 0 : this.getEndDate().hashCode() );
         result = 37 * result + ( getDepartments() == null ? 0 : this.getDepartments().hashCode() );
         result = 37 * result + ( getEmployees() == null ? 0 : this.getEmployees().hashCode() );
         result = 37 * result + ( getJobs() == null ? 0 : this.getJobs().hashCode() );

         return result;
    }


}

