/*Generated by WaveMaker Studio*/

package com.nwissuesjan25.wmstudio;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import javax.persistence.PrimaryKeyJoinColumn;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;


import java.util.Arrays;

import javax.persistence.Transient;
import javax.persistence.CascadeType;
import javax.persistence.UniqueConstraint;



/**
 * Table9 generated by hbm2java
 */
@Entity
@Table(name="`TABLE9`"
    ,schema="HR"
)

public class Table9  implements java.io.Serializable {

    private BigDecimal id;
    private BigDecimal column2;

    public Table9() {
    }


    @Id 
    

    @Column(name="`ID`", nullable=false)
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }

    

    @Column(name="`COLUMN2`")
    public BigDecimal getColumn2() {
        return this.column2;
    }
    
    public void setColumn2(BigDecimal column2) {
        this.column2 = column2;
    }





    public boolean equals(Object o) {
         if (this == o) return true;
		 if ( (o == null )) return false;
		 if ( !(o instanceof Table9) )
		    return false;

		 Table9 that = (Table9) o;

		 return ( (this.getId()==that.getId()) || ( this.getId()!=null && that.getId()!=null && this.getId().equals(that.getId()) ) );
    }

    public int hashCode() {
         int result = 17;

         result = 37 * result + ( getId() == null ? 0 : this.getId().hashCode() );

         return result;
    }


}

